### ISSUE TITLE
Information about sound hacking project

### ISSUE THREAD

**Issue by wassfila** [dragonman225/stm32f469-usbaudio#6]
Hi @dragonman225 ,

This is simply an information ticket as I did not find any other way to contact you. I found this project while looking for resources about SM32 Audio USB and you know well that it's a non properly covered topic.

My goal is to create a pio library for the USB audio drivers so that they get as easy to use as any Arduino like library but with the full flexibility of the cubemx environment. an example here https://github.com/STM32Libs/f411_piocube_lib_blink

My further goal is to play around with real time audio processing between microcontrollers and PC (Python / web), I've seen in your website that you're interested in web as well, I recently started experimenting with the audio web API

If you're interested, you can have a look at this website, all is intended to open source on github (I'm doing this as a hobby), I even have a discord server to ease up communications and updates.

https://soundhacking.github.io/

**Comment by dragonman225** [comment]
Hi @wassfila, I've added my contact information on my website [here](https://dragonman225.js.org/about#https://www.notion.so/cdb93934a8b840798d3652da0dfdf350).

The sound hacking project looks interesting. I guess it would be cool to use voice to command web applications. Thanks for sharing!

**Comment by wassfila** [comment]
Thanks a lot. I've been recently more focusing on FrontEnd webdev and left web and uC Audio a bit aside, but I keep your contact for when I switch back to audio.
For info regarding voice recognition, we did that in another open source project just not in web but in Python, see details here (it was a long running project I participated to)
https://thesoundofaiosr.github.io/
https://github.com/TheSoundOfAIOSR/project_common

**Comment by dragonman225** [comment]
Wow, I'm also doing frontend web development these days and audio became more of a hobby.
The AI project looks cool (and there are nice videos!) I'll check it out when I have free time.

**Comment by wassfila** [comment]
cool, on which domain do you apply FrontEnd ? and if I may ask which environment do you work with
I do Front End for Python related data science and analysis and main real application I did is home automation, sensors and control GUI 
https://github.com/MicroWebStacks/NextHomeControl
here I have thoughts and links about Web Frameworks evolution
https://github.com/orgs/MicroWebStacks/discussions

**Comment by dragonman225** [comment]
I build frontend stuff mostly for "tools for thought" applications, whose goals are to improve the way people think about, create, and communicate ideas with computers. Technically it involves [rich-text](https://github.com/ProseMirror/prosemirror) [editing](https://github.com/ianstormtaylor/slate), [canvas](https://github.com/tldraw/tldraw) [interfaces](https://github.com/excalidraw/excalidraw), [real-time](https://github.com/yjs/yjs) [collaboration](https://www.inkandswitch.com/peritext/), videoconferencing, etc — different products have different mixes of those. I mostly build with React + JavaScript/TypeScript, and a little Node.js.
This is a small toy that I made https://dragonman225.js.org/jade.html

Home automation seems fun! I have a friend who is a firmware engineer, and he bought a bunch of ESP32 dev boards to control switches in his house without leaving his desk.

**Comment by wassfila** [comment]
Looks really cool, sort of mind map, todo, notes,... thanks for all the links, interesting libraries.
I'm curious about the arrows, must be canvas I guess, no need for the pain of SVG. For reasons such as high res or scalable print export, I dive in SVG for some hobby projects. This is the closest I have to your topics, it's about managing a lot of nodes (graph) where labels keep readable at all times (collisions-physics), but it was just a proof of concept that made me realize graphs are quite hard to represent : https://github.com/NetworkGraphs/graphysics

**Comment by dragonman225** [comment]
The arrows are SVGs, since it's easier to add interactivity, for example, to show a context menu when right-clicking on just the arrow shape. I extracted the algorithm into a library and explained how it works [here](https://github.com/dragonman225/curved-arrows).

I took a look at your project [graphysics](https://github.com/NetworkGraphs/graphysics), it's fancy! The "[collision](https://github.com/NetworkGraphs/graphysics#nodes-collisions-to-ensure-labels-visibility)" function reminds me of a mind-mapping app called Mindnode, which also has a similar technique to prevent node overlapping: when you drop a node on top of other nodes, it moves them to make a space. And the "[attract](https://github.com/NetworkGraphs/graphysics#force-attract-neighbors)" function seems useful since it provides strong visual feedback when exploring "what's nearby".

Graph visualization is quite a topic for people building tools for thought, note-taking apps like [Logseq](https://logseq.com/) and [Obsidian](https://obsidian.md/) have a "graph" feature to show how notes are linked together. [Cotoami](https://github.com/cotoami/cotoami) is exploring the graph-based "[concept-mapping](https://github.com/cotoami/cotoami#concept-mapping)" technique. However, those are more of cool than useful. No one has shown how graph can be a killer feature for note-taking yet.

**Comment by wassfila** [comment]
> Graph visualization is quite a topic for people building tools for thought, note-taking apps like [Logseq](https://logseq.com/) and [Obsidian](https://obsidian.md/) have a "graph" feature to show how notes are linked together. [Cotoami](https://github.com/cotoami/cotoami) is exploring the graph-based "[concept-mapping](https://github.com/cotoami/cotoami#concept-mapping)" technique. However, those are more of cool than useful. No one has shown how graph can be a killer feature for note-taking yet.

totally agree.
Thanks for the links and explanation.
